# Generated by Django 5.1 on 2024-08-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognew',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
